apiVersion: v1
kind: Pod
metadata:
  name: frontend
spec:
  containers:
  - name: app
    image: hello-world
    resources:
      requests:
        memory: "64Mi" #Garantizado
        cpu: "250m" #Garantizado
      limits:
        memory: "128Mi"
        cpu: "500m"
