apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
stringData:
  companyName: "K8S"
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: con-demoapp
      image: icuadrosaforo255/dockerdemo:configmaps
      env:
        - name: COMPANY_NAME
          valueFrom:
            secretKeyRef:
              name: mysecret2
              key: companyName
