apiVersion: v1
kind: Secret
metadata:
  name: mysecret2
type: Opaque
stringData:
  fromConfig: |
    {
      "From": "KUBERNETES SECRETS 1"
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: con-demoapp
      image: icuadrosaforo255/dockerdemo:configmaps
      volumeMounts:
      - name: vl-config
        mountPath: "/app/config"
        readOnly: true
  volumes:
  - name: vl-config
    secret:
      secretName: mysecret2
      items:
      - key: fromConfig
        path: config.json
